services:
  - type: web
    name: pdf-toolkit-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    build:
      packages:
        - poppler-utils
